language: node_js
node_js:
- node
branches:
  only:
  - master
sudo: false
notifications:
  email: false
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/updateData.sh; fi'
env:
  global:
    - ENCRYPTION_LABEL: "056c956745cc"
    - COMMIT_AUTHOR_EMAIL: "thuey100@gmail.com"
