language: node_js
node_js:
- node
branches:
  only:
  - master
sudo: false
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_056c956745cc_key -iv $encrypted_056c956745cc_iv
  -in deploy_key.enc -out deploy_key -d
script: bash ./scripts/updateData.sh
env:
  global:
    - ENCRYPTION_LABEL: "056c956745cc"
    - COMMIT_AUTHOR_EMAIL: "thuey100@gmail.com"
