language: node_js
node_js:
- node
branches:
  only:
  - master
sudo: false
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_056c956745cc_key -iv $encrypted_056c956745cc_iv
  -in jsplaygrounds_rsa.enc -out jsplaygrounds_rsa -d
